AWSTemplateFormatVersion: 2010-09-09
Description: Rust AWS Serverless API
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 30
  Api:
    OpenApiVersion: 3.0.2
    Cors:
      AllowMethods: "'OPTIONS,POST,GET'"
      AllowHeaders: "'Origin, Authorization, Accept, Content-Type'"
      AllowOrigin: "'*'"

Resources:
  SampleServerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-lambda-function
      Description: Sample Server Lambda Function
      CodeUri: lambda.zip
      Runtime: provided.al2
      Handler: bootstrap.is.real.handler
      MemorySize: 1024
      Environment:
        Variables:
          RUST_BACKTRACE: 1
      Events:
        api:
          Type: Api
          Properties:
            Path: /sample
            Method: any

Outputs:
  SampleServerApi:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  SampleServerFunction:
    Value: !GetAtt SampleServerFunction.Arn
  SampleServerFunctionIamRole:
    Value: !GetAtt SampleServerFunctionRole.Arn
